### ISSUE TITLE
登录接口不起来

### ISSUE THREAD

**Issue by dmodaii** [alwxkxk/akoa#1]
-  运行后端项目
 
```
Error: Cannot find module 'koa-body-parsers'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/d.hilter/code/node/vue+koa+amdin/akoa/node_modules/koa-better-body/utils.js:11:21)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

-  然后安装  koa-body-parsers

- 然后前端登录时候, 后端报错 （node_modules/co/index.js）

```
发生异常: TypeError
TypeError: Cannot set property 'save' of undefined
    at Object.keys.forEach (/Users/d.hilter/code/node/vue+koa+amdin/akoa/node_modules/koa-body-parsers/index.js:18:22)
    at Array.forEach (native)
    at Object.module.exports [as bodyParsers] (/Users/d.hilter/code/node/vue+koa+amdin/akoa/node_modules/koa-body-parsers/index.js:17:24)
    at Object.setParsers (/Users/d.hilter/code/node/vue+koa+amdin/akoa/node_modules/koa-better-body/utils.js:121:9)
    at Object.plugin (/Users/d.hilter/code/node/vue+koa+amdin/akoa/node_modules/koa-better-body/index.js:49:13)
    at plugin.next (<anonymous>)
    at onFulfilled (/Users/d.hilter/code/node/vue+koa+amdin/akoa/node_modules/co/index.js:65:19)
    at /Users/d.hilter/code/node/vue+koa+amdin/akoa/node_modules/co/index.js:54:5
    at Promise (<anonymous>)
    at Object.co (/Users/d.hilter/code/node/vue+koa+amdin/akoa/node_modules/co/index.js:50:10)
    at converted (/Users/d.hilter/code/node/vue+koa+amdin/akoa/node_modules/koa-convert/index.js:17:15)
    at dispatch (/Users/d.hilter/code/node/vue+koa+amdin/akoa/node_modules/koa-better-router/node_modules/koa-compose/index.js:44:32)
    at /Users/d.hilter/code/node/vue+koa+amdin/akoa/node_modules/koa-better-router/node_modules/koa-compose/index.js:36:12
    at /Users/d.hilter/code/node/vue+koa+amdin/akoa/node_modules/koa-better-router/index.js:547:46
    at dispatch (/Users/d.hilter/code/node/vue+koa+amdin/akoa/node_modules/koa-compose/index.js:42:32)
    at next (/Users/d.hilter/code/node/vue+koa+amdin/akoa/node_modules/koa-compose/index.js:43:18)
```

请问这个怎么解决啊
非常希望能解决下

**Comment by alwxkxk** [comment]
如果怀疑是koa-body-parsers安装有问题。因为并没有直接用到koa-body-parsers，是koa-better-body这个模块用到。应该直接安装npm  install 就可以运行的，具体原因及解决办法我也不确定，我提供两个方法你先试试：
1.删除原项目 ，重新git clone ，然后将代理指向国内， 重新安装试试看行不行。

```
 npm config set registry https://registry.npm.taobao.org
npm install
```

2.删除原项目 ，重新git clone ，将package-lock.json文件删除，再尝试安装：npm install。

另外在说明文档上README.md补充了npm run init 来检查mysql redis的是否正确运行并初始化。


如果你能解决此问题，麻烦再次反馈给我，十分感谢。

**Comment by dmodaii** [comment]
解决了， 十分感谢， 正打算用你这个项目弄一下前段端， 考虑用mongo
